/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bussines_logic.main;
import data.*;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;

/**
 *
 * @author Harold
 */
public class SeenInsurance extends javax.swing.JFrame {
    public static boolean[] bool$ = new boolean[6];

    /**
     * Creates new form SeenInsurance
     */
    public SeenInsurance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PriceI = new javax.swing.JLabel();
        ChulitoI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CompanyILabel = new javax.swing.JLabel();
        AssistensI = new javax.swing.JLabel();
        DaysI = new javax.swing.JLabel();
        PeopleI = new javax.swing.JLabel();
        AnimalI = new javax.swing.JCheckBox();
        InsectI = new javax.swing.JCheckBox();
        LuggageI = new javax.swing.JCheckBox();
        MurderedI = new javax.swing.JCheckBox();
        TropicalI = new javax.swing.JCheckBox();
        DeadI = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel52.setBackground(new java.awt.Color(255, 102, 102));
        jLabel52.setFont(new java.awt.Font("Gautami", 1, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("TRAVEL INSURANCE");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(30, 10, 270, 70);

        jLabel51.setBackground(java.awt.Color.cyan);
        jLabel51.setOpaque(true);
        jPanel1.add(jLabel51);
        jLabel51.setBounds(0, 0, 540, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price: $");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 250, 63, 45);
        jPanel1.add(PriceI);
        PriceI.setBounds(90, 250, 208, 45);

        ChulitoI.setBackground(new java.awt.Color(255, 255, 255));
        ChulitoI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comprobado (1).png"))); // NOI18N
        ChulitoI.setBorder(null);
        ChulitoI.setBorderPainted(false);
        ChulitoI.setContentAreaFilled(false);
        ChulitoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChulitoIActionPerformed(evt);
            }
        });
        jPanel1.add(ChulitoI);
        ChulitoI.setBounds(310, 260, 40, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 260, 40, 30);

        jLabel1.setText("People amount:");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 200, 100, 10);

        jLabel4.setText("Num. Assistens");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 100, 14);

        jLabel5.setText("Days amount:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 90, 14);

        jLabel6.setText("Company:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 110, 50, 14);

        CompanyILabel.setText("              ");
        jPanel1.add(CompanyILabel);
        CompanyILabel.setBounds(90, 110, 70, 14);

        AssistensI.setText("                ");
        jPanel1.add(AssistensI);
        AssistensI.setBounds(110, 140, 50, 14);

        DaysI.setText("          ");
        jPanel1.add(DaysI);
        DaysI.setBounds(110, 170, 60, 14);

        PeopleI.setText("           ");
        jPanel1.add(PeopleI);
        PeopleI.setBounds(110, 200, 60, 14);

        AnimalI.setBackground(new java.awt.Color(255, 255, 255));
        AnimalI.setText("Animal Bite");
        AnimalI.setEnabled(false);
        jPanel1.add(AnimalI);
        AnimalI.setBounds(180, 160, 77, 23);

        InsectI.setBackground(new java.awt.Color(255, 255, 255));
        InsectI.setText("Insect Bite");
        InsectI.setEnabled(false);
        jPanel1.add(InsectI);
        InsectI.setBounds(180, 180, 77, 23);

        LuggageI.setBackground(new java.awt.Color(255, 255, 255));
        LuggageI.setText("Luggage");
        LuggageI.setEnabled(false);
        jPanel1.add(LuggageI);
        LuggageI.setBounds(300, 180, 81, 23);

        MurderedI.setBackground(new java.awt.Color(255, 255, 255));
        MurderedI.setText("Murdered");
        MurderedI.setEnabled(false);
        jPanel1.add(MurderedI);
        MurderedI.setBounds(300, 160, 81, 23);

        TropicalI.setBackground(new java.awt.Color(255, 255, 255));
        TropicalI.setText("Tropical Diseases");
        TropicalI.setEnabled(false);
        jPanel1.add(TropicalI);
        TropicalI.setBounds(300, 140, 110, 23);

        DeadI.setBackground(new java.awt.Color(255, 255, 255));
        DeadI.setText("Accidental Dead");
        DeadI.setEnabled(false);
        jPanel1.add(DeadI);
        DeadI.setBounds(180, 140, 110, 23);

        jLabel11.setText("Coverage");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 110, 60, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        for(Safe It: main.Safes.values()){
            if(GUI.PlaceI.equals(It.getPlace()) && 
                    GUI.SelectedPackage.equals(It.getSafeCompany() + " - " + It.getName())){
                DeadI.setSelected(It.getCoverage()[0]);
                AnimalI.setSelected(It.getCoverage()[1]);
                InsectI.setSelected(It.getCoverage()[2]);
                TropicalI.setSelected(It.getCoverage()[3]);
                MurderedI.setSelected(It.getCoverage()[4]);
                LuggageI.setSelected(It.getCoverage()[5]);
                bool$ = It.getCoverage();
                CompanyILabel.setText(It.getSafeCompany());
                AssistensI.setText(It.getAssistance());
                DaysI.setText(GUI.DaysI.toString());
                PeopleI.setText(GUI.PeopleI);
                System.out.println(It.getPrice());
                Integer Price = GUI.DaysI * Integer.parseInt(It.getPrice());
                PriceI.setText(Price.toString());
                
            }
        }
        
    }//GEN-LAST:event_formComponentShown

    private void ChulitoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChulitoIActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<6 ;i++){
            if (bool$[i]){
                GUI.PassInsurance[i] = "true";
            }else{
                GUI.PassInsurance[i] = "false";
            }
        }
        GUI.PassInsurance[6] = CompanyILabel.getText();
        GUI.PassInsurance[7] = AssistensI.getText();
        GUI.PassInsurance[8] = DaysI.getText();
        GUI.PassInsurance[9] = PeopleI.getText();
        GUI.PassInsurance[10] = PriceI.getText();
        
        GUI.AuxI.put(GUI.AuxI.size(), GUI.PassInsurance);
        GUI.Aux.put(3, GUI.AuxI);
        GUI.Services.put(login.User, GUI.Aux);
        FileOutputStream fileStream = null;
        try{
            fileStream = new FileOutputStream("Service.obj");
            ObjectOutputStream os = new ObjectOutputStream(fileStream);
            for(HashMap It : GUI.Services.values()){
                os.writeObject(It);
            }
            os.close();
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_ChulitoIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI.main(new String[1]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeenInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeenInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeenInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeenInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeenInsurance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AnimalI;
    private javax.swing.JLabel AssistensI;
    private javax.swing.JButton ChulitoI;
    private javax.swing.JLabel CompanyILabel;
    private javax.swing.JLabel DaysI;
    private javax.swing.JCheckBox DeadI;
    private javax.swing.JCheckBox InsectI;
    private javax.swing.JCheckBox LuggageI;
    private javax.swing.JCheckBox MurderedI;
    private javax.swing.JLabel PeopleI;
    private javax.swing.JLabel PriceI;
    private javax.swing.JCheckBox TropicalI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
