/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;

/**
 *
 * @author Estudiante
 */
public class SeenFly extends javax.swing.JFrame {

    /**
     * Creates new form SeenF
     */
    public SeenFly() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        AmPrice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChulitoF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AmSeats = new javax.swing.JLabel();
        AmClass = new javax.swing.JLabel();
        AmDeparture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Gautami", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Are you sure?");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(80, 20, 210, 32);

        jLabel31.setBackground(new java.awt.Color(255, 153, 0));
        jLabel31.setOpaque(true);
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 540, 80);

        AmPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(AmPrice);
        AmPrice.setBounds(105, 237, 208, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price: $");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(36, 237, 63, 45);

        ChulitoF.setBackground(new java.awt.Color(255, 255, 255));
        ChulitoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comprobado (1).png"))); // NOI18N
        ChulitoF.setBorder(null);
        ChulitoF.setBorderPainted(false);
        ChulitoF.setContentAreaFilled(false);
        ChulitoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChulitoFActionPerformed(evt);
            }
        });
        jPanel1.add(ChulitoF);
        ChulitoF.setBounds(330, 250, 40, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 250, 40, 30);

        jLabel1.setText("Seats amount:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 70, 14);

        jLabel4.setText("Class:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 30, 14);

        jLabel5.setText("Depature date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 80, 14);

        AmSeats.setText("                ");
        jPanel1.add(AmSeats);
        AmSeats.setBounds(120, 110, 170, 14);

        AmClass.setText("                         ");
        jPanel1.add(AmClass);
        AmClass.setBounds(80, 140, 240, 14);

        AmDeparture.setText("                       ");
        jPanel1.add(AmDeparture);
        AmDeparture.setBounds(120, 170, 210, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        AmSeats.setText(GUI.PassFly[0]);
        AmClass.setText(GUI.PassFly[1]);
        AmDeparture.setText(GUI.PassFly[2]);
        AmPrice.setText(GUI.PassFly[3]);
    }//GEN-LAST:event_formComponentShown

    private void ChulitoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChulitoFActionPerformed
        // TODO add your handling code here:
        
        GUI.AuxF.put(GUI.AuxF.size(), GUI.PassFly);
        GUI.Aux.put(1, GUI.AuxF);
        GUI.Services.put(login.User, GUI.Aux);
        FileOutputStream fileStream = null;
        try{
            fileStream = new FileOutputStream("Service.obj");
            ObjectOutputStream os = new ObjectOutputStream(fileStream);
            for(HashMap It : GUI.Services.values()){
                os.writeObject(It);
            }
            os.close();
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_ChulitoFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI.main(new String[1]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeenFly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeenFly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeenFly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeenFly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeenFly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmClass;
    private javax.swing.JLabel AmDeparture;
    private javax.swing.JLabel AmPrice;
    private javax.swing.JLabel AmSeats;
    private javax.swing.JButton ChulitoF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
