/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bussines_logic.main;
import data.*;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;

/**
 *
 * @author Estudiante
 */
public class SeenCar extends javax.swing.JFrame {

    /**
     * Creates new form SeenC
     */
    public SeenCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PriceC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChulitoC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CompanyC = new javax.swing.JLabel();
        PlateC = new javax.swing.JLabel();
        ColorC = new javax.swing.JLabel();
        CapacityC = new javax.swing.JLabel();
        GPSC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        PriceC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(PriceC);
        PriceC.setBounds(90, 240, 208, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price: $");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 240, 63, 45);

        ChulitoC.setBackground(new java.awt.Color(255, 255, 255));
        ChulitoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comprobado (1).png"))); // NOI18N
        ChulitoC.setBorder(null);
        ChulitoC.setBorderPainted(false);
        ChulitoC.setContentAreaFilled(false);
        ChulitoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChulitoCActionPerformed(evt);
            }
        });
        jPanel1.add(ChulitoC);
        ChulitoC.setBounds(300, 250, 40, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 250, 40, 30);

        jLabel47.setBackground(new java.awt.Color(255, 102, 102));
        jLabel47.setFont(new java.awt.Font("Gautami", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Are you sure?");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(60, 20, 180, 32);

        jLabel46.setBackground(new java.awt.Color(0, 204, 102));
        jLabel46.setOpaque(true);
        jPanel1.add(jLabel46);
        jLabel46.setBounds(0, 0, 540, 80);

        jLabel1.setText("Company:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 100, 60, 14);

        jLabel4.setText("Plate:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 50, 14);

        jLabel5.setText("Color:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 50, 14);

        jLabel6.setText("Capacity:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 160, 70, 14);

        jLabel7.setText("GPS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 180, 30, 14);

        CompanyC.setText(" ");
        jPanel1.add(CompanyC);
        CompanyC.setBounds(100, 100, 60, 14);

        PlateC.setText(" ");
        jPanel1.add(PlateC);
        PlateC.setBounds(90, 120, 50, 14);

        ColorC.setText(" ");
        jPanel1.add(ColorC);
        ColorC.setBounds(90, 140, 50, 14);

        CapacityC.setText(" ");
        jPanel1.add(CapacityC);
        CapacityC.setBounds(90, 160, 60, 14);

        GPSC.setText(" ");
        jPanel1.add(GPSC);
        GPSC.setBounds(80, 180, 50, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        for(Car It: main.Cars.values()){
            if(It.getPlace().equals(GUI.CountrySelected) &&
                    ((String)It.getModel() + " - " + It.getName() + " - " + 
                            It.getPlate()).equals(GUI.CarSelected)){
                CompanyC.setText(It.getCompany());
                PlateC.setText(It.getPlate());
                ColorC.setText(It.getColor());
                CapacityC.setText(It.getPeople());
                if(It.isGps()){
                    GPSC.setText("Yes");
                }else{
                    GPSC.setText("No");
                }
                PriceC.setText(It.getPrice());
            }
        }
        Integer Price = Integer.parseInt(GUI.Capacity$);
        Price *= Integer.parseInt(PriceC.getText());
        GUI.PassCars[0] = CompanyC.getText();
        GUI.PassCars[1] = PlateC.getText();
        GUI.PassCars[2] = ColorC.getText();
        GUI.PassCars[3] = CapacityC.getText();
        GUI.PassCars[4] = GPSC.getText();
        GUI.PassCars[5] = Price + "";
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void ChulitoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChulitoCActionPerformed
        // TODO add your handling code here:
        GUI.AuxC.put(GUI.AuxC.size(), GUI.PassCars);
        GUI.Aux.put(2, GUI.AuxC);
        GUI.Services.put(login.User, GUI.Aux);
        FileOutputStream fileStream = null;
        try{
            fileStream = new FileOutputStream("Service.obj");
            ObjectOutputStream os = new ObjectOutputStream(fileStream);
            for(HashMap It : GUI.Services.values()){
                os.writeObject(It);
            }
            os.close();
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_ChulitoCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI.main(new String[1]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeenCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeenCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeenCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeenCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeenCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapacityC;
    private javax.swing.JButton ChulitoC;
    private javax.swing.JLabel ColorC;
    private javax.swing.JLabel CompanyC;
    private javax.swing.JLabel GPSC;
    private javax.swing.JLabel PlateC;
    private javax.swing.JLabel PriceC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
