/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bussines_logic.main;
import data.User;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */

public class Sing_in extends javax.swing.JFrame {
    public void Usave(){
        FileOutputStream fileStream = null;
        try{
            fileStream = new FileOutputStream("UserList.obj");
            ObjectOutputStream os = new ObjectOutputStream(fileStream);
            for(data.User It : main.Users.values()){
                os.writeObject(It);
            }
            os.close();
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
        
    }
    public void SingIn(){
        
        int Usercount = main.Users.size();
        boolean signup = true; 
        User UserToAdd = null;
        if(UserField.getText().length()!= 0 && PassField.getText().length()!= 0
                && EmailField.getText().length()!= 0 && LastField.getText().length()!= 0
                && NameField.getText().length()!= 0 && AddField.getText().length()!= 0
                && CellField.getText().length()!= 0 && PhoneField.getText().length()!= 0){
            if(EmailField.getText().contains("@") && EmailField.getText().contains(".")){
                for(User it : main.Users.values()){
                    if(!UserField.getText().equals(it.getUser())){
                        UserToAdd = new User(UserField.getText(),
                                PassField.getText(), NameField.getText(), LastField.getText(),
                                PhoneField.getText(), CellField.getText(), AddField.getText(), 
                                EmailField.getText(), CreditField.getText(), IdField.getText(), false);
                    }else{
                        signup = false;
                    } 
                }
                if(signup){
                    main.Users.put(Usercount++,UserToAdd);
                    JOptionPane.showMessageDialog(rootPane, "You has registered successfully", "Well done", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    login.main(new String[1]);
                    Usave();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Usser alredy exists", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Invalid email.", "Error", JOptionPane.ERROR_MESSAGE);
                EmailField.requestFocus();
                EmailField.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
    /**
     * Creates new form Sing_in
     */
    public Sing_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "Convert2Lambda"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        LastField = new javax.swing.JTextField();
        CellField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        AddField = new javax.swing.JTextField();
        Sign_Up = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Log_in = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        CreditField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(273, 470));
        setMinimumSize(new java.awt.Dimension(273, 470));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 110, 17);

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 134, 38, 16);

        jLabel3.setText("Lastname:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 163, 60, 16);

        jLabel4.setText("User:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 47, 31, 16);

        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 76, 60, 16);

        jLabel6.setText("Phone:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 191, 40, 16);

        jLabel7.setText("Cellphone:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 219, 61, 16);

        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 253, 51, 16);

        jLabel9.setText("Email:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 105, 36, 16);

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserField);
        UserField.setBounds(134, 47, 101, 22);
        getContentPane().add(EmailField);
        EmailField.setBounds(134, 105, 101, 22);
        getContentPane().add(NameField);
        NameField.setBounds(134, 134, 101, 22);
        getContentPane().add(LastField);
        LastField.setBounds(134, 163, 101, 22);
        getContentPane().add(CellField);
        CellField.setBounds(134, 221, 101, 22);
        getContentPane().add(PhoneField);
        PhoneField.setBounds(134, 192, 101, 22);
        getContentPane().add(AddField);
        AddField.setBounds(134, 250, 101, 22);

        Sign_Up.setText("Sign Up");
        Sign_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_UpActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_Up);
        Sign_Up.setBounds(41, 378, 77, 25);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(182, 378, 53, 25);

        jLabel10.setText("Have an a account?");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(41, 416, 111, 16);

        Log_in.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Log_in.setForeground(new java.awt.Color(0, 0, 255));
        Log_in.setText("Log in");
        Log_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_inMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_inMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_inMouseExited(evt);
            }
        });
        getContentPane().add(Log_in);
        Log_in.setBounds(192, 418, 33, 14);

        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PassField);
        PassField.setBounds(134, 76, 101, 22);

        jLabel11.setText("Credit card:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 279, 68, 16);

        jLabel12.setText("Id:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 311, 16, 16);

        IdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Enter(evt);
            }
        });
        getContentPane().add(IdField);
        IdField.setBounds(134, 308, 101, 22);
        getContentPane().add(CreditField);
        CreditField.setBounds(134, 279, 101, 22);

        jLabel14.setBackground(new java.awt.Color(255, 102, 0));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 280, 40);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 280, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void Log_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_inMouseClicked
        // TODO add your handling code here:
        login.main(new String[1]);
        this.dispose();
    }//GEN-LAST:event_Log_inMouseClicked

    @SuppressWarnings("null")
    private void Sign_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_UpActionPerformed
        // TODO add your handling code here:
       SingIn();
        
    }//GEN-LAST:event_Sign_UpActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Font font = Log_in.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        Log_in.setFont(font.deriveFont(attributes));
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown
 
    private void Log_inMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_inMouseEntered
        // TODO add your handling code here:
        Log_in.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Log_inMouseEntered

    private void Log_inMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_inMouseExited
        // TODO add your handling code here:
        Log_in.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Log_inMouseExited

    private void Enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enter
        // TODO add your handling code here:
        int code = evt.getKeyCode(); 
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){          
            SingIn();
        }
         
    }//GEN-LAST:event_Enter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sing_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sing_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sing_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sing_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sing_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddField;
    private javax.swing.JTextField CellField;
    private javax.swing.JTextField CreditField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField IdField;
    private javax.swing.JTextField LastField;
    private javax.swing.JLabel Log_in;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton Sign_Up;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
